### PR TITLE
CMake improvements

### PR DESCRIPTION
**Pull request by scivision**
* CMake CI: only trigger CMake CI to avoid needless running of Autotools workflows when only CMake has changed
* remove redundant, unused CMake presets
* improve how libsc links to system libraries

### CODE REVIEW

**Comment by cburstedde** [comment]
> * CMake CI: only trigger CMake CI to avoid needless running of Autotools workflows when only CMake has changed
> * remove redundant, unused CMake presets
> * improve how libsc links to system libraries
> 
> You can view, comment on, or merge this pull request online at:

Thanks, this is generally working!  Yet I noticed, when I run

    cmake ~/work/p4est/sc/ -Dmpi=no
    cmake ~/work/p4est/sc/ -Dmpi=yes

I get

    CMake Error at cmake/config.cmake:158 (message):
      MPI used, but sc_config.h is not configured for MPI
    Call Stack (most recent call first):
      CMakeLists.txt:17 (include)

Similarly for the other way around.
Is there anything to be done about it?

**Comment by scivision** [comment]
When reconfiguring MPI from on to off or vice versa, the build directory needs to be deleted

**Comment by cburstedde** [comment]
Thanks!

**Comment by cburstedde** [comment]
CI fails on Windows now. Would you be able to looki into it?

**Pull request merged**
