### PR TITLE
CMake enhancements

### PR DESCRIPTION
**Pull request by scivision**
* CI: unify techniques with p4est
* test: simplify, better approach for Windows

### CODE REVIEW

**Comment by gghosh8495** [comment]
@cburstedde It seems qsort_r may not be the issue because as per the configure script output it is able to detect qsort_r in BSD format. That is what we would expect on a mac. I wish there was a way to look at error log on git actions.

**Comment by scivision** [comment]
there is a way to have Github Actions auto-upload the config.log on error. Another way is to just print it like:

```yaml
    - name: print config log
      if: ${{ failure() }}
      run: cat build/CMakeFiles/CMakeError.log
 ```

**Comment by scivision** [comment]
the config error is a coincidence -- the Github Actions .yml file was mistakenly set to run when ci_cmake.yml changed instead of ci_darwin.yml

**Comment by cburstedde** [comment]
I see, thanks. Manual merging.

**Pull request merged**
