### PR TITLE
qsort_r warning fix

### PR DESCRIPTION
**Pull request by gghosh8495**
# Title Macro for selecting the correct qsort_r prototype depending on BSD or GNU system

Following up on issue # .

Proposed changes:
Create a macro which links with the correct prototype -> define and set C macro's SC_HAVE_GNU_QSORT_R and SC_HAVE_BSD_QSORT_R -> Use them in source code to select the the correct prototype and comparators

### CODE REVIEW

**Comment by cburstedde** [comment]
Are these issues resolved on the current branches for qsort_r and Darwin CI?

**Comment by gghosh8495** [comment]
@cburstedde No I was hoping to get your opinion on this issue. 

The config log shows:
configure: - SC -------------------------------------------------
We did not find a recent lua containing the function lua_createtable.
This is OK if the following does not matter to you:
Including sc_lua.h in your code will abort the compilation.
You can fix this by compiling a working lua and pointing LIBS to it.

make  all-am
make[1]: Entering directory '/home/runner/work/libsc/libsc/checkdebug_sharedBLAS'
  CC       libb64/src_libsc_la-cencode.lo
  CC       libb64/src_libsc_la-cdecode.lo
  CC       libb64/b64dec.o
make[1]: *** No rule to make target ' config/sc_v4l2.m4', needed by 'all-am'.  Stop.
make[1]: *** Waiting for unfinished jobs....
  CC       iniparser/sc_iniexample-iniexample.o
make[1]: Leaving directory '/home/runner/work/libsc/libsc/checkdebug_sharedBLAS'
make: *** [Makefile:1170: all] Error 2

I was not sure what to do here.

**Comment by gghosh8495** [comment]
I tried adding the config/sc_v4l2.m4 file to the Makefile.am but the linux CI did not like it.

**Comment by cburstedde** [comment]
> The config log shows:
> configure: - SC -------------------------------------------------
> We did not find a recent lua containing the function lua_createtable.
> This is OK if the following does not matter to you:
> Including sc_lua.h in your code will abort the compilation.
> You can fix this by compiling a working lua and pointing LIBS to it.
> 
> make  all-am
> make[1]: Entering directory '/home/runner/work/libsc/libsc/checkdebug_sharedBLAS'
>   CC       libb64/src_libsc_la-cencode.lo
>   CC       libb64/src_libsc_la-cdecode.lo
>   CC       libb64/b64dec.o
> make[1]: *** No rule to make target ' config/sc_v4l2.m4', needed by 'all-am'.  Stop.
> make[1]: *** Waiting for unfinished jobs....
>   CC       iniparser/sc_iniexample-iniexample.o
> make[1]: Leaving directory '/home/runner/work/libsc/libsc/checkdebug_sharedBLAS'
> make: *** [Makefile:1170: all] Error 2
> 
> I was not sure what to do here. 

Is this issue present on the latest develop/respecively prev3-develop?  I would
believe it repaired.

**Comment by gghosh8495** [comment]
@cburstedde No it seems to be specific to the develop branch.

**Pull request closed without merging**
