### PR TITLE
cmake: add pkg-config generate and determine version from git describe

### PR DESCRIPTION
**Pull request by scivision**

### CODE REVIEW

**Comment by scivision** [comment]
that error code 135 on Windows CI is just something that happens intermittently on GitHub Actions with Windows in general. I.e. just rerunning the workflow clears it

**Comment by cburstedde** [comment]
Thanks! I'm just testing this and I'm getting on `cmake path/to/source/p4est/sc`:
(This seems to be independent of updating `git describe --abbrev=4 --match 'v*'`.)

```
-- SC 2.8.2
-- NAME_MISMATCHED (missing: REQUIRED_VARS VERSION_VAR) 
CMake Error at /usr/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:195 (message):
  Unknown keywords given to FIND_PACKAGE_HANDLE_STANDARD_ARGS():
  "REASON_FAILURE_MESSAGE"
Call Stack (most recent call first):
  cmake/Modules/FindMPI.cmake:1741 (find_package_handle_standard_args)
  cmake/config.cmake:8 (find_package)
  CMakeLists.txt:21 (include)
```

**Comment by scivision** [comment]
I'm going to remove that backported FindMPI.cmake, as it causes issues with older CMake

**Comment by cburstedde** [comment]
> I'm going to remove that backported FindMPI.cmake, as it causes issues with older CMake

Sounds great.  My preference is simplicity always.

**Comment by scivision** [comment]
OK I think this is ready to go, thanks

**Comment by cburstedde** [comment]
Cool, thanks! As a side note, we never had much luck with the github release mechanism, so I'm not endorsing github releases. Especially the p4est/sc submodule never was included properly.

**Comment by cburstedde** [comment]
Testing this, I find a couple differences with autotools regarding the .pc:
 * The file name would ideally look like libsc-2.8.2.25-afe3-dirty.pc
 * Can .pc file name and "Version:" be the same as by git describe --dirty --abbrev=4 --match="v*"?
 * Can we remove the "Requires: sc" line?
 * I'd prefer not to expose iniparser at all, not even privately, just to add the objects to the library.
 * (Note to self: Make sure -lsc shows up in the autotools .pc, and quote the variables.)

**Comment by scivision** [comment]
Do you also want libb64 to also be just an object like iniparser?

**Comment by cburstedde** [comment]
> Do you also want libb64 to also be just an object like iniparser?

That would be great, then .pc: Libs.private becomes the same as Libs and might no longer be needed.

The default --prefix for autoconf is $PWD/local, would this be an easy thing to do with cmake?

I'm about to integrate up to the current tip, please don't force push at this point. Thanks again!

**Comment by cburstedde** [comment]
Is there anything I should make install in the autotools build (such as cmake related files)?

**Comment by scivision** [comment]
In the next PR I put all non-CMakeLIsts.txt Cmake files under cmake/

**Pull request merged**
