### PR TITLE
Add scda API

### PR DESCRIPTION
**Pull request by tim-griesbach**
# Add scda API

This PR introduces in libsc the API of the scda file format (https://doi.org/10.48550/arXiv.2307.06789), a file-oriented data format suitable for parallel, partition-independent disk I/O. The main purpose of the format is to abstract any parallelism and provide sufficient structure as a foundation for a generic and flexible archival and checkpoint/restart.

We only add the API for now to gather feedback on the API and also on the format as introduced in the arxiv preprint linked above. We appreciate any feedback on scda and its concrete API in libsc.

Proposed changes:
- Add  the API of the scda file format in `sc_scda.h`
- Restructure IO module in the Doxygen documentation and introduce a page for the scda workflow
- General polishing and completion of the documentation in `sc_io.h`

### CODE REVIEW

**Comment by cburstedde** [comment]
Thanks; I'm wondering whether there are any news. Would it make sense to merge it now and continue later?

**Comment by cburstedde** [comment]
Can I ask to resolve the current conflicts against a recent branch develop?

**Comment by tim-griesbach** [comment]
> Thanks; I'm wondering whether there are any news. Would it make sense to merge it now and continue later?

From my side there are no news and I think it makes sense to merge it now and continue later.



> Can I ask to resolve the current conflicts against a recent branch develop?

Sure, I pushed a merge commit that resolves the merge conflict against recent develop.

**Comment by tim-griesbach** [comment]
I made all changes as we discussed and from my side this PR is ready to be merged.

**Comment by cburstedde** [comment]
Thanks! As of recently, I'd like to grow the doc/release_notes.txt file with every update. In this case, there may be multilpe, one for sc_io and one for sc_scda, possibly one for docs -- as you see fit.

**Comment by tim-griesbach** [comment]
> Thanks! As of recently, I'd like to grow the doc/release_notes.txt file with every update. In this case, there may be multilpe, one for sc_io and one for sc_scda, possibly one for docs -- as you see fit.

I added release notes for version 2.8.6.

**Pull request merged**
